### ISSUE TITLE
Can't blank properties

### ISSUE THREAD

**Issue by stesvis** [mark-gerarts/automapper-plus#12]
First of all I am a big fan of the .NET AutoMapper and thank you so much for creating this for PHP!

Is there a way to blank out properties?
For example if my source object has a property like this:
```
[
    'description' => ''
]
```

the AutoMapper will ignore it. My goal is to ignore it if null, but to overwrite it if it's an empty string.

Basically if someone wants to delete an optional text field, they can't.
Maybe there is already a way to do that, if so, could you let me know?
Or otherwise can it be implemented?

Thanks!

**Comment by mark-gerarts** [comment]
Hi there,

I want to make sure I understand the situation correctly. Let's say you have this setup:

```php
<?php

class A
{
    public $description;
}

class B
{
    public $description;
}


$config = new AutoMapperConfig();
$config->registerMapping(A::class, B::class);
$mapper = new AutoMapper($config);

$a = new A();
$b = new B();
```

Am I correct that you want to achieve the following:

```php
<?php

$b->description = 'some value';

$a->description = '';
$b = $mapper->mapToObject($a, $b);
// $b->description is now the empty string. This is okay.

$a->description = null;
$b = $mapper->mapToObject($a, $b);
// $b is now overwritten to be `null`. This is something you don't want -
// if the source property is null, you want to ignore it. 
```

**Comment by stesvis** [comment]
Thanks for your prompt reply.
Yes that would be the ideal scenario.

Right now in both cases after the mapping b->description is always 'some value'.

It seems that the mapping is ignored unless a->description is not empty and not null.

**Comment by mark-gerarts** [comment]
Alright, I'll try to look into this the following days/weeks. I'm either gonna provide an option to achieve this behaviour, or implement a new operation.

One small thing though, which version are you using? I tested the sample code using the latest version, and there `$b->description` would always be overwritten, instead of it remaining 'some value'. This seems a bit weird to me, unless you're using a slightly different configuration?

**Comment by stesvis** [comment]
Thanks,
this is what I have right now:
`"mark-gerarts/auto-mapper-plus": "^1.1",`

I have one more question:

**Model: Guide** has some relationships
 ```
class Guide extends Model
{
    // ...

    public function bikes()
    {
        return Bike::whereIn("id", $this->stable()
            ->select("bike_id")
            ->get()
            ->toArray());
    }

    public function tours()
    {
        return $this->hasMany(Tour::class);
    }
}
```

**DTO: GuideDTO** has the matching properties

```
class GuideDTO
{
    // ...

    public $bikes;
    public $tours;
}
```

**Mapper config**
```
$config->registerMapping(Guide::class, GuideDTO::class)->reverseMap();
$config->registerMapping(Bike::class, BikeDTO::class)->reverseMap();
```

**ISSUE**

`$mapper->map($guide, GuideDTO::class);`

bikes: "App\\Models\\Guide::bikes must return a relationship instance."
tours: is properly mapped

NOTE: If i do this, it works fine:
```
$bikeDTOs = $mapper->mapMultiple($guide->bikes()->get(), BikeDTO::class);
$guideDTO = $mapper->map($guide, GuideDTO::class);
$guideDTO->bikes = $bikeDTOs;
```

Is there a solution to map everything in one shot with just this?
`$guideDTO = $mapper->map($guide, GuideDTO::class);`

**Comment by stesvis** [comment]
Actually I am wrong, I don't seem to be able to ignore $guides.
This still gives me the same error:
```
$config->registerMapping(Organization::class, OrganizationDTO::class)
                **->forMember('guides', Operation::ignore())**
                ->forMember('tours', Operation::mapTo(TourDTO::class))
                ->reverseMap();
```

How can I tell it to not map $guides, so i can do it manually?

**Comment by mark-gerarts** [comment]
Thanks for the detailed write-up! This'll definitely help with debugging. Unfortunately, I don't have much time to take a look at this issue at this moment. I'll try to get back to you next week!

**Comment by Koronos** [comment]
Any new about this?

**Comment by mark-gerarts** [comment]
I have to admit I kinda lost this one out of sight. I can't make any promises when this will be resolved as I'm a bit busy the following weeks. Anyway: 

- The issue might have been resolved already due to a previous fixed issue involving Doctrine. The first step would be to check this.
- The feature request is still open to implement. I'll look into this after the first issue has been resolved.

**Comment by mark-gerarts** [comment]
I've had some time to review your issue @stesvis. It seems to be that Eloquent's __isset method checks if a property could represent a relationship. Since your `bikes` method doesn't actually return a relationship, but a query result, an exception gets thrown. Returning for example `$this->hasMany(...)` instead in the `bikes` method, results into a mapped DTO. However, this'll likely change the behaviour you want, so your temporary solutions seems to me the best fix for this.

**Comment by stesvis** [comment]
Thanks for looking into it!

**Comment by mark-gerarts** [comment]
It is now possible to ignore `null` properties on the source object by using `$options->ignoreNullProperties()`. This is available on master, and will be part of the next release.
