### ISSUE TITLE
Map to nested objects

### ISSUE THREAD

**Issue by BoShurik** [mark-gerarts/automapper-plus#22]
Hello! I have the following code:
```php
$order = new Order();
$item = new Item();
$item->setName('Item Name');
$item->setPrice(1000);
$order->setItems([$item]);

dump($order);

// DTO haven't price property*
$dto = $mapper->map($order, OrderDTO::class);

dump($dto);

$order = $mapper->mapToObject($dto, $order);

dump($order);
```

Output:
```
App\Model\Order {#23
  -items: array:1 [
    0 => App\Model\Item {#24
      -name: "Item Name"
      -price: 1000
    }
  ]
}
App\DTO\OrderDTO {#33
  +items: array:1 [
    0 => App\DTO\ItemDTO {#28
      +name: "Item Name"
    }
  ]
}
App\Model\Order {#23
  -items: array:1 [
    0 => App\Model\Item {#31
      -name: "Item Name"
      -price: null
    }
  ]
}
```

Expected output:
```
App\Model\Order {#23
  -items: array:1 [
    0 => App\Model\Item {#24
      -name: "Item Name"
      -price: 1000
    }
  ]
}
App\DTO\OrderDTO {#33
  +items: array:1 [
    0 => App\DTO\ItemDTO {#28
      +name: "Item Name"
    }
  ]
}
App\Model\Order {#23
  -items: array:1 [
    0 => App\Model\Item {#31
      -name: "Item Name"
      -price: 1000
    }
  ]
}
```

Reproducer: https://github.com/BoShurik/automapper-plus-issue

**Comment by mark-gerarts** [comment]
Hi. First off, I appreciate you took the effort to create a small project to reproduce the issue. Really helpful!

Now, the problem here is that the `ItemDTO` does not have a `$price` property. So when an `ItemDTO` gets mapped back to an `Item` again, we don't have any way of knowing what the original price was. Adding a `$price` property to the DTO would solve the problem. If this isn't an option for you, I'm afraid there isn't much we can do about this (that I can think of for now).

**Comment by BoShurik** [comment]
Yes, but if we add `price` property to `Order` and not add it to `OrderDTO` we will have the right value at the third step for that field. Maybe there is a way to pass destination object somehow? May custom mapper help?
