### ISSUE TITLE
Mapping operations without source property required

### ISSUE THREAD

**Issue by ed-posinitskiy** [mark-gerarts/automapper-plus#8]
There is a `@TODO`  on `AutoMapperPlus\Configuration\Mapping::shouldCheckForSourceProperty()` method.

Indeed certain operations needs extra Interface to skip property existence check.

For instance, I don't want certain properties to be mapped into destination object. The way it works now is perfect (with `Ignore` operation) but there is one problem: when I specify this operation on virtual property (i.e. in Laravel there is a lot of magic happens on models) `forMember` method will try to ensure source property exist. But it has no sense due to meaning of `Ignore` operation.

Also you have great `PropertyAccessorInterface` object, please utilize it to check property can be reached instead of default PHP function within `forMember` method.

Thanks in advance, great Tool!

**Comment by mark-gerarts** [comment]
Yes, these are very valid points. In fact, as a short term solution I removed the checking of source properties entirely a few days ago, in https://github.com/mark-gerarts/automapper-plus/commit/a9e5590d2bcb08f84ef46c96ac0d30361923a3fa. This isn't part of release yet though, it's only available on `dev-master`. So if this is causing you problems, you can check out this version for now.

The reason for removing this behaviour is indeed because it doesn't really work with dynamic properties.  For the long term it might be better to work with an interface or something similar. but this will require some more thought.

**Comment by ed-posinitskiy** [comment]
Thank you for such a quick response! As a workaround I made a custom Operation extended from `MapFrom` operation to skip property check.

**Comment by ed-posinitskiy** [comment]
Thanks for update!
